### ISSUE TITLE
Globals Section Bug

### ISSUE THREAD

**Issue by masonry47** [thejoshsmith/craft-fab-permissions#14] opened 2020-02-18 15:57 UTC
Hi there!

Since installing the plugin, we are having issues with the "Globals" section. 

When clicking on "Globals", we get

"Trying to get property of non-object"

We are on:

Craft 3.3.19
Plugin Version: 1.2.3

All goes back to normal when disabling the plugin.  

Thanks for your help!

**Comment by thejoshsmith** [comment] 2020-02-18 20:04
Hey @masonry47, I'll have a look at this one for you tonight!

**Comment by masonry47** [comment] 2020-02-18 20:39
Thanks!

<http://www.builtbymasonry.com/>

ROSS BRANDON * Digital Director *

MASONRY <http://www.builtbymasonry.com/>     | Office: 512.417.9930
 | Mobile:
512.694.0852

**Comment by masonry47** [comment] 2020-02-28 14:59
@thejoshsmith 

Hi there, were you ever able to take a look at this issue?  Thanks!

**Comment by thejoshsmith** [comment] 2020-02-29 08:53
Hi @masonry47, sorry I was bit under the weather last week. I've just tried to replicate on my local dev site and I'm having trouble reproducing the error.

Could you please send me a screenshot, web.log or database to me@joshsmith.dev and I'll investigate further. 

Cheers!

**Comment by thejoshsmith** [comment] 2020-04-17 18:04
Closing due to inactivity.

**Comment by masonry47** [comment] 2020-04-17 18:27
Hey Josh

Apologies, we do still have interest in using the plugin and actually just today investigating as we have updated to most current version of Craft along with your plugin, and do get the same error. remind me again what to provide we will do it.  Thanks!

**Comment by thejoshsmith** [comment] 2020-04-18 21:14
No worries at all @masonry47! I was just tidying up the issues 😄. If you could please send me a copy of your database and composer.json/composer.lock files I should be able to replicate the issue you're seeing.

**Comment by thejoshsmith** [comment] 2020-05-02 08:58
@masonry47 now marking as resolved 😄 

Issue was identified as:

> It had to do with the fact that the Translations plugin, created its own version of "Drafts" for Globals, since Craft natively does not have "Drafts" for globals.  Which makes sense, if the client sends a Global content entry for translation, when it comes back the client needs to review the content before making it live, hence the Translations plugin made a "draft" for globals and I think that is where the conflict was.   I think Acclaro updated how they handle that now with the latest version of Craft, So I think it is a non issue now.

**Closed by thejoshsmith** 2020-05-02 08:58 UTC
